"""Initial migration

Revision ID: 06ce698f9f32
Revises: 
Create Date: 2025-02-10 23:11:46.143624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06ce698f9f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.alter_column('chats', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'chats', 'subjects', ['subject_id'], ['id'])
    op.drop_column('enrollments', 'last_accessed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('last_accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.alter_column('chats', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('chats', 'subject_id')
    # ### end Alembic commands ###
