"""Remote changes

Revision ID: 8443c095f365
Revises: aec2331b5310
Create Date: 2025-02-09 18:35:20.483398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8443c095f365'
down_revision: Union[str, None] = 'aec2331b5310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_constraint('chats_subject_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'subject_id')
    op.drop_column('chats', 'name')
    op.add_column('enrollments', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'last_accessed_at')
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chats_subject_id_fkey', 'chats', 'subjects', ['subject_id'], ['id'])
    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_upload_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('grade >= 0', name='grades_grade_check'),
    sa.PrimaryKeyConstraint('id', name='grades_pkey')
    )
    # ### end Alembic commands ###
